### ISSUE TITLE
Getting Curl timeout error during product patch request

### ISSUE THREAD

**Issue by benjam-es** [nztim/mailchimp#14]
Is there a way to prevent the Curl timeout error occurring during product patch request.

**Comment by nztim** [comment]
If the cause is a communications failure between your server and Mailchimp then the code can't prevent it. In my experience the occasional timeout is pretty normal.

You can use try/catch and retry a few times on failure to make the code more robust. I use queued jobs whenever I can so retrying is built in and speed doesn't matter so much.

**Comment by benjam-es** [comment]
I discovered in my case it was an error in what I was sending, but because it was within variants, within products, there was no error returned. I opted to change to sending the variants separately.

**Comment by nztim** [comment]
Glad to hear you got it sorted! :)
