### ISSUE TITLE
Permanently deleted contact status is "not found" instead of "cleansed"

### ISSUE THREAD

**Issue by hqgamingclubadmin** [nztim/mailchimp#31]
I have permanently deleted a contact from my audience list. Retrieving the status from this contact now returns "not found".
I was expecting that "cleansed" would be the status I'd get for a permanently deleted contact.

The problem now is that there is no way to differentiate between a new contact and a contact which is permanently deleted.

If you then try to subscribe/update this contact you will receive a mailchimp api error

**"xxxx@xxxx was permanently deleted and cannot be re-imported. The contact must re-subscribe to get back on the list"**

Steps to reproduce : 

1. Add a contact in mailchimp
2. permanently delete this contact
3. get status from contact by using Mailchimp::status

Any way around this?

**Comment by nztim** [comment]
My understanding is that deleting a contact from an audience/list is permanent and the only way to re-subscribe is for the user to re-subscribe (with double-opt-in) via a Mailchimp-hosted form. This is a Mailchimp policy and applies to the web interface and the API.

I don't think 'cleaned' would be a correct status because that describes an address automatically removed by MC for bouncing: https://mailchimp.com/help/about-cleaned-contacts

From memory, the behaviour you describe is correct in that it reflects what the API returns, but I will double check and come back.

**Comment by nztim** [comment]
I've had a look and it's as above, I've added a test to confirm the behaviour and to see if things change:
https://github.com/nztim/mailchimp/blob/master/tests/StatusTest.php#L27

A deleted user's status is the same as one who has never subscribed and my expectation is that this is by design, so that a user can be 'forgotten' from a privacy/GDPR perspective. 

If there was a concrete way to identify this failure we could have a specific exception for it, but it's a 400 error with a text description that could potentially change. You could try catching 400 errors and redirecting those users to a MC form. Even if the error wasn't this problem the request still wasn't successful for some reason.  

Hope that helps!
